name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java: [ 8, 11 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
