name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java_version:
          - 8
          - 11
          - 17
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.java_version }}

      - env:
          DEBIAN_FRONTEND: noninteractive
        run: >
          sudo apt-get -qq update &&
          sudo apt-get -qq install libatlas3-base

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build --warning-mode all
